#!/bin/bash

# Change path and name to your snowflake log
# or use parameter 1

SNOWFLAKELOG=/var/log/snowflake/proxy.log
if [ -n "$1" ] ; then
    SNOWFLAKELOG=$1
fi

cat "${SNOWFLAKELOG}" \
| grep connections \
| sed -f sed/log.sed \
| awk -F ';' -f awk/log.awk \
| sed 's#^#'$HOSTNAME';#'
